### ISSUE TITLE
checkCountDepth: FilterCellProportion explicitly needs to be a list

### ISSUE THREAD

**Issue by jenzopr** [rhondabacher/SCnorm#1]
Hey Rhonda!
Thank you a lot for your preprint and the effort you put into this package.

When using checkCountDepth with two or more conditions, the FilterCellProportion call in line 40 of checkCountDepth.R expects itself to be a list with two or more components with the respective parameter value.

I had to circumvent the problem by explicitly calling
```
checkCountDepth(Data = ExampleData, Conditions = Conditions, PLOT = F, FilterCellProportion = list(c(0.1),c(0.1))) 
```
to make your example code run.

Thanks again a lot for your effort :+1: 
Jens

**Comment by rhondabacher** [comment]
Thank Jens! This has been fixed :)
