### ISSUE TITLE
Error when running more than one condition

### ISSUE THREAD

**Issue by livnatje** [rhondabacher/SCnorm#12]
Hi Rhonda,

I really like the SCnorm approach and would love to try it on my scRNA-seq data!
I managed to run it on the example datasets, but on my data, when I provide more than one condition I get the following error:

Gene filter is applied within each condition.
89 genes were not included in the normalization due to having less than 5 non-zero values.
23 genes were not included in the normalization due to having less than 5 non-zero values.
A list of these genes can be accessed in output, see vignette for example.
Finding K for Condition SS1
Trying K = 1
Trying K = 2
Trying K = 3
Trying K = 4
Finding K for Condition SS2
Trying K = 1
Trying K = 2
Plotting count-depth relationship for normalized data...
Error in density.default(Slopes[useg]) : 'x' contains missing values

Any idea why/how to fix it?

Thanks a lot!
Livnat

**Comment by rhondabacher** [comment]
Hi Livnat,

Thanks for using SCnorm! Are you running the latest version? I added some checks to account for what was causing that error message in a fairly recent update. To update to the newest version please install SCnorm using:
library(devtools)
devtools::install_github("rhondabacher/SCnorm")
(Also check the new vignette as the usage of some functions may have slightly changed in the last couple of weeks as I've been preparing for submitting to BioConductor.)

If you are still receiving the error with the newest version or have any other questions, please let me know.

**Comment by livnatje** [comment]
Great! It's working.
Thank you so much :)
