### ISSUE TITLE
plotcountdepth function not working

### ISSUE THREAD

**Issue by chintanparekh2301** [rhondabacher/SCnorm#18]
Hi,
I tried running the plotcountdepth function on a numeric matrix with 192 columns and 12408  genes (genes as row names). I don't get an error message but it just keeps running for ever with no results (run through R studio, 32 core machine 128 GB RAM).
Here's the code I used 
library("BiocInstaller", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.4")
library("BiocParallel", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.4")
library("SCnorm", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.4")

setwd('/home/bioinfoadmin/Desktop/Chintan parekh')
scnormdata1 <- readRDS('mergedatamatrix5.rds')
countDeptEst <- plotCountDepth(Data = scnormdata1, FilterCellProportion = .1)

I tried with Conditions where 
Conditions = rep(c(1), each= 192)
That didn't work either

It works fine when I use a dataset containing a subset (upto 5000 genes) but does not work when I use the whole dataset.

I installed using the following:
library(devtools)
devtools::install_github("rhondabacher/SCnorm")

Any ideas?
Thank you very much

**Comment by rhondabacher** [comment]
Hi,

Thanks for using SCnorm.

I agree that the size of your data should not be a problem. It could be your system does not cooperate well with the BiocParallel setup. I suggest installing SCnorm using the development branch, which is exactly the same but parallelizes differently.  You can install by typing:
library(devtools)
devtools::install_github("rhondabacher/SCnorm", ref="devel")

Please let me know if this resolves your issue.

Best,
Rhonda

**Comment by chintanparekh2301** [comment]
Hi Rhonda,
It was UMI data and worked fine when I used the option dithercounts = True
Thank you
