### ISSUE TITLE
SCnorm fails to converge in multiple datasets

### ISSUE THREAD

**Issue by zji90** [rhondabacher/SCnorm#23]
Hi,
I am using SCnorm on multiple datasets generated by Fluidigm, but it fails to converge in at least two of them even though I have set ditherCounts=T,FilterCellNum=20,FilterExpression=1. Applying more stringent filtering criteria (for example FilterCellNum=50) will result in "At least one condition has less then 100 genes that pass the specified filter. Check the quality of your data or filtering criteria." I do have a condition that has around 30 cells. I wonder what kind of criteria I should apply to get SCnorm run. Thanks!

**Comment by rhondabacher** [comment]
Hi Zhicheng,

I'm guessing you have you tried setting FilterCellNum to the default of 10?

I think given the smaller number of cells and filter, the majority of genes are being removed from the normalization and evaluation procedure. That can make the evaluation densities less smooth and broader..which makes the modes difficult to estimate accurately. You can try loosening the parameter Thresh, to be Thresh = .15 (default is Thresh = .1), which controls how close to zero each density needs to be. But I would also take a close look at the evaluation plots (they are made for each value of K if you have PrintProgressPlots=TRUE) and see how close to 0 the densities are. If a given value of K visually looks like it -should- be converging, i.e all are centered around zero, then you can choose to set K via the parameter K in the SCnorm() function. Note that you will get a warning message if you do that as I don't generally recommend it to typical users and it's not needed in most cases.

Hope that helps!
Rhonda
