### ISSUE TITLE
results function not working

### ISSUE THREAD

**Issue by yangithub33** [rhondabacher/SCnorm#26]
Hello,
I am using SCnorm. after normalization, to extract normalized count by using results function, but I got NULL even using example.
here is the simple script
source("https://bioconductor.org/biocLite.R")
biocLite("SCnorm")
library(SCnorm)
data(ExampleSimSCData)
Conditions = rep(c(1), each= 90)
NormData <- SCnorm(Data=ExampleSimSCData, Conditions=Conditions)
normDataMatrix <- results(NormData,type = "NormalizedData")

when looked at the NormData by str(NormData), there are 10 slots, could you please let me know which slot that the normalized data is?

It will be really appreciated if you could give me a clue.

Best,
Ting

**Comment by rhondabacher** [comment]
Hi Ting,

Thanks for bringing this to my attention. I implemented SingleCellExperiment and did not change the documentation accordingly.

You should be able to do the following to get the normalized data:

library(SingleCellExperiment)
normcounts(NormData)
