### ISSUE TITLE
useSpikes error

### ISSUE THREAD

**Issue by bvieth** [rhondabacher/SCnorm#27]
Dear Rhonda,

in the newest version of SCnorm (1.4.5), I am running into an issue when I want to use spike-ins for between-condition scaling (see example R script). This has not happened for me using earlier versions (e.g. 1.0.0).

The following error message is printed:
`Scaling data between conditions...
Error in CondNormMat[scalegenes, ] : subscript out of bounds`

As far as I can see the error occurs because the qgenes vector in the function `scaleNormMultCont()` does not contain for all ExpGroups the spike-ins and therefore the subsetting `qgenes[Genes[which(SingleCellExperiment::isSpike(OrigData))]]` returns NA values.

When I ran the same example with useSpikes = TRUE, it runs thru without an error. Even though I am making a dummy example data set using your example data set for convenience, this error still occurs for my real data set.

Kind regards,
Beate

[SCnorm_useSpikes.txt](https://github.com/rhondabacher/SCnorm/files/2875562/SCnorm_useSpikes.txt)
[SCnorm_sessionInfo.txt](https://github.com/rhondabacher/SCnorm/files/2875563/SCnorm_sessionInfo.txt)

**Comment by rhondabacher** [comment]
Hi Beate,

Thanks for letting me know and pointing out the source of the error! I was able to fix it and have updated with a new version on Github v1.5.7.

Please let me know if you have any other issues.

Best,
Rhonda
