### ISSUE TITLE
pdf copy and dev.off incorrect order

### ISSUE THREAD

**Issue by golharam** [rhondabacher/SCnorm#6]
In checkCountDepth, line 85 and 86 need to be reversed.

You need to call dev.off prior to copy the pdf file.  Alternatively, I think when you call pdf(), you can pass the filename to use so you don't need to copy in the end.

**Comment by rhondabacher** [comment]
Thanks for mentioning this issue that occurred when x11() forwarding was not being used. I've changed the checkCountDepth function to always save the output PDF and no longer attempts to print to screen.
