### ISSUE TITLE
checkCountDepth quietly writes plot to file

### ISSUE THREAD

**Issue by davismcc** [rhondabacher/SCnorm#8]
Hi Rhonda

Taking a first look at `SCnorm` - exciting and potentially very useful package. But why on earth does checkCountDepth write a plot to a pdf file instead of producing a plot in the current plotting device? This behaviour means that the plot doesn't appear in a Jupyter notebook running this code and makes it a pain to view plots when running code on a cluster.

Could I suggest that you change this default behaviour? If users want to save plots to file themselves, then it is trivially easy for them to do so by wrapping the call to `checkCountDepth` in pdf() ... dev.off() and they have full control. Even better (IMO) would be to use `ggplot2` and return the ggplot object from `checkCountDepth`, which can be displayed, saved, customised by the user as they wish.

Thanks for your excellent work on the package and best wishes,
Davis

**Comment by rhondabacher** [comment]
Hello Davis,

Thanks for your suggestion. An earlier version of SCnorm printed to screen, and also saved a pdf. Unfortunately, a number of our early users had trouble with the print to screen on certain clusters. Consequently, we left the save to pdf option but removed the print to screen. To accommodate more flexible plotting I have added the option SavePDF. The default is SavePDF =TRUE and will write the plot to file. For your purposes, you may wish to set SavePDF=FALSE, which will print to screen or current device. You may wrap plotting options around the checkCountDepth call to customize.

Thanks,
Rhonda

**Comment by davismcc** [comment]
Hi Rhonda

Fair enough! Thanks a lot for the change - that's working very nicely for me now. 

Best
Davis
